"""
setup_ddcolor_code.py

Fetches the DDColor MODEL CODE (not the weights) from the official GitHub
repository and places it in  src/vendor/ddcolor/.

    python scripts/setup_ddcolor_code.py            # fetch if missing
    python scripts/setup_ddcolor_code.py --force    # fetch again

Why this script exists
  DDColor's own code imports from a copy of "basicsr" bundled inside its
  repository. If we simply installed or cloned it, that bundled copy would
  clash with the real "basicsr" package that GFPGAN and Real-ESRGAN need
  later (two different packages with the same name). The model only needs 5
  small, pure-PyTorch files, so we copy just those and change 4 import lines
  to local ones (from basicsr.archs.ddcolor_arch_utils.X -> from .X).

Safety
  * The commit is pinned, and every file is checked against a SHA-256
    checksum, so you get exactly the code that was reviewed.
  * Source: https://github.com/piddnad/DDColor  (Apache License 2.0).
    The licence text and a NOTICE listing our changes are saved alongside.

Uses only Python's standard library.
"""

import hashlib
import re
import sys
import urllib.error
import urllib.request
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
TARGET_DIR = PROJECT_ROOT / "src" / "vendor" / "ddcolor"

COMMIT = "2adb63f2656ac41cbdf7b894cddd94121a3faf13"
RAW_BASE = f"https://raw.githubusercontent.com/piddnad/DDColor/{COMMIT}/"
UTILS = "basicsr/archs/ddcolor_arch_utils/"

# (path in the DDColor repo, file name here, expected SHA-256 of the original)
FILES = [
    ("ddcolor/model.py", "model.py",
     "e8e30115aa65a9558db33641c999001d1735c444402890898b47b2cc52b37c25"),
    (UTILS + "unet.py", "unet.py",
     "2b72fd6ef60d73f033cd3b2a3b4737d5371d4190b6410883e4d987d8417df1b2"),
    (UTILS + "convnext.py", "convnext.py",
     "f03e339488570aa79e0690719546317a375ca85bd8a9e1e5f2c797cda033db45"),
    (UTILS + "transformer_utils.py", "transformer_utils.py",
     "61d99be451ef0717eaa1bf84ecfd29f9c4224ac1e5a35d68a963c4b97f4dbd0b"),
    (UTILS + "position_encoding.py", "position_encoding.py",
     "beb5b3b52f2cc4f2dfc9f312cdc5d712468ff1d2985be7471a94a0c37a8c01d6"),
    ("LICENSE", "LICENSE",
     "43070e2d4e532684de521b885f385d0841030efa2b1a20bafb76133a5e1379c1"),
]

NOTICE_TEXT = f"""DDColor model code (vendored)

Source:  https://github.com/piddnad/DDColor
Commit:  {COMMIT}
Licence: Apache License 2.0 (see the LICENSE file in this folder)
Authors: Xiaoyang Kang et al., DAMO Academy, Alibaba Group
Paper:   "DDColor: Towards Photo-Realistic Image Colorization via Dual Decoders" (ICCV 2023)

Changes made by this project (Apache 2.0, section 4b):
  * model.py: the four lines  "from basicsr.archs.ddcolor_arch_utils.X import ..."
    were changed to  "from .X import ...",  so the model no longer depends on
    the copy of basicsr bundled in the DDColor repository.
  * All other files are unmodified copies.

This folder is generated by scripts/setup_ddcolor_code.py.
"""

IMPORT_PATTERN = re.compile(r"from basicsr\.archs\.ddcolor_arch_utils\.")


def fetch(remote_path: str) -> bytes:
    url = RAW_BASE + remote_path
    request = urllib.request.Request(
        url, headers={"User-Agent": "photo-restorer-setup/1.0"})
    with urllib.request.urlopen(request, timeout=30) as response:
        return response.read()


def main() -> int:
    force = "--force" in sys.argv[1:]
    expected_names = [local for _, local, _ in FILES] + ["NOTICE.txt"]
    if not force and all((TARGET_DIR / name).is_file() for name in expected_names):
        print(f"DDColor code is already in {TARGET_DIR}. (Use --force to refetch.)")
        return 0

    TARGET_DIR.mkdir(parents=True, exist_ok=True)
    print(f"Fetching DDColor code (commit {COMMIT[:10]}) ...")
    downloaded = {}
    for remote_path, local_name, expected_hash in FILES:
        try:
            data = fetch(remote_path)
        except (urllib.error.URLError, TimeoutError, OSError) as error:
            print(f"  FAILED to download {remote_path}: {error}")
            print("  Check your internet connection and try again.")
            return 1
        actual_hash = hashlib.sha256(data).hexdigest()
        if actual_hash != expected_hash:
            print(f"  CHECKSUM MISMATCH for {remote_path}")
            print(f"    expected {expected_hash}")
            print(f"    got      {actual_hash}")
            print("  The file differs from the version this project was "
                  "tested with, so nothing was installed.")
            return 1
        downloaded[local_name] = data
        print(f"  ok  {local_name}")

    # Only write files after ALL downloads passed their checks.
    for local_name, data in downloaded.items():
        text = data.decode("utf-8")
        if local_name == "model.py":
            text, replaced = IMPORT_PATTERN.subn("from .", text)
            if replaced != 4:
                print(f"  Unexpected: rewrote {replaced} imports, expected 4.")
                return 1
            if re.search(r"^\s*(from|import)\s+basicsr", text, re.MULTILINE):
                print("  A basicsr import is still present; aborting.")
                return 1
        (TARGET_DIR / local_name).write_text(text, encoding="utf-8", newline="\n")
    (TARGET_DIR / "NOTICE.txt").write_text(NOTICE_TEXT, encoding="utf-8")

    print(f"\nDone. DDColor model code is in {TARGET_DIR}")
    return 0


if __name__ == "__main__":
    sys.exit(main())